name: Deploy Lambda Function with test script 

on:
  #push:
  #  branches:
  #   - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
    Terraform:
        runs-on: ubuntu-latest

        env:
            terraform_version: 1.6.6
            AWS_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: ${{ env.terraform_version }}
            
            - name: Terraform Init
              run: terraform init
            - name: Terraform Plan
              run: terraform plan
            - name: Terraform Apply
              run: terraform apply -auto-approve

    test:
        runs-on: ubuntu-latest
        needs: Terraform

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: Make test script executable
              run: chmod +x pre-setup-script.sh

            - name: Run test script
              run: |
                ./pre-setup-script.sh

              